### ISSUE TITLE
`KrausPfeifer1998` classify fails

### ISSUE THREAD

**Issue by brycefrank** [brycefrank/pyfor#62]
```{python}
Traceback (most recent call last):
  File "C:\Users\bfrank70\Miniconda3\envs\pyfor_env\lib\site-packages\pandas\core\indexes\base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'v_i'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bfrank70\Miniconda3\envs\pyfor_env\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\bfrank70\Miniconda3\envs\pyfor_env\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\bfrank70\Programming\pyfor\pyfortest\test_pyfor.py", line 388, in test_classify
    self.test_kp_filter.classify(self.test_cloud)
  File "C:\Users\bfrank70\Programming\pyfor\pyfor\ground_filter.py", line 269, in classify
    grid.cloud.data.points["classification"][grid.cloud.data.points['v_i'] <= self.g + self.w] = ground_int
  File "C:\Users\bfrank70\Miniconda3\envs\pyfor_env\lib\site-packages\pandas\core\frame.py", line 2980, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\bfrank70\Miniconda3\envs\pyfor_env\lib\site-packages\pandas\core\indexes\base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'v_i'

```

**Comment by brycefrank** [comment]
The `.classify` method was not operating on the original points.
